version: '3.8'

services:
  sekta:
    image: sekta
    platform: linux/arm64/v8
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: SEKTA
    environment:
      - TOKEN=
      - APPLICATIONID=
      - SEKTA=
      - DATABASE_URL